"""baseline: documents, extractions, validations, reviews

Revision ID: b8f3978fedfd
Revises: 
Create Date: 2026-07-20 12:28:34.139157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8f3978fedfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED', 'VALIDATED', 'REVIEW', 'COMPLETED', 'FAILED', 'ESCALATED', 'REJECTED', name='document_status'), nullable=False),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=256), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_error', sa.String(length=512), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=True)
    op.create_index(op.f('ix_extractions_overall_confidence'), 'extractions', ['overall_confidence'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=512), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_decision'), 'reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_reviews_document_id'), 'reviews', ['document_id'], unique=True)
    op.create_table('validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('overall', sa.String(length=16), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_document_id'), 'validations', ['document_id'], unique=True)
    op.create_index(op.f('ix_validations_overall'), 'validations', ['overall'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validations_overall'), table_name='validations')
    op.drop_index(op.f('ix_validations_document_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_reviews_document_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_decision'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_extractions_overall_confidence'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
